### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jaysimon** [DCASE-REPO/bulbul_bird_detection_dcase2018#4]
When I try to run run.sh, I got this, Where could I download chern_test.csv?

Traceback (most recent call last):
  File "./code/create_filelists.py", line 21, in <module>
    with open("%s/%s.csv"%(args.path, filelist), 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/houwei/02-dataset/04-task3-bird/list/chern_test.csv'

**Comment by danstowell** [comment]
Ah yes you're right. I've put separated blank submission files here:
https://figshare.com/articles/Bird_Audio_Detection_example_submission_files_separated_for_DCASE_Challenge_2018_Task_3/7149959
